version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: example_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../:/var/www/html
    links:
      - php
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    build: mysql
    container_name: example_mysql
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - mysql:/var/lib/mysql
  php:
    build: php
    container_name: example_php
    tty: true
    volumes:
      - ../:/var/www/html:cached
    links:
      - mysql

volumes:
  mysql:
